owid/owid-catalog-py

owid/catalog/datasets.py, owid/catalog/meta.py, tests/test_datasets.py
To support the ability of knowing whether a dataset is out of date, we add two types of checksum support:
- `Dataset.metadata.source_checksum`: record the checksum of the ingredients used to make this dataset
- `Dataset.checksum()`: calculate the checksum of the files in this dataset, if this one is used as an ingredient for another recipe
=> Add checksum support to datasets

owid/catalog/frames.py, owid/catalog/tables.py, tests/test_frames.py
This PR causes `Table.to_feather()` to modify data types on save to the most compact types possible. For example, small numbers may be converted from `int64` to `int8` or `uint8`. The conversion is opt-out, meaning it is applied by default.
=> enhance: Pack data frames into compact types on Table save

owid/catalog/__init__.py, owid/catalog/catalogs.py, owid/catalog/datasets.py, owid/catalog/meta.py, tests/test_catalogs.py, tests/test_datasets.py
A `LocalCatalog` is just a folder full of datasets, themselves just folders full of tables. Some of the nice catalog interface only got tested for the `RemoteCatalog`, and remained broken locally.
The `LocalCatalog()` would firstly not correctly work unless it had been indexed. Secondly, it would fail on `load()` of a table because the `_base_uri` had not been set.
This fix automatically reindexes a local catalog if no index is present, and secondly fixes the load method so that you can properly load local datasets.
=> fix #21: allow loading from local catalogs

README.md, owid/catalog/datasets.py, owid/catalog/frames.py, owid/catalog/tables.py, owid/catalog/utils.py, poetry.lock, pyproject.toml, tests/test_datasets.py, tests/test_frames.py, tests/test_tables.py, tests/test_utils.py
I've found that we're losing metadata on several places when manipulating with columns. I fixed what I could and added mention to README. Some operations like `t.columns = ...` might be non-trivial to do, but at least we're aware of it now.
=> fix(metadata): fix lost metadata

owid/catalog/meta.py, owid/catalog/tables.py
Add fields `published_by` and `publisher_source` to `Source` object which are necessary to get parity between ETL and grapher. In the future when we refine grapher data model we might consolidate these, but for the time being this is the easiest option.
Also add helper functions for loading metadata from yaml files. This is still proof-of-concept, if we decide it's a good idea we'll refactor it and add more tests & validations (gonna create a task for that).
`underscore` function was improved to handle columns from WB dataset, but that one is also good candidate for future refactoring.
=> enhance(grapher): align metadata for grapher and ETL

.github/workflows/python-package.yml, README.md, owid/catalog/catalogs.py, owid/catalog/datasets.py, owid/catalog/variables.py, poetry.lock, pyproject.toml, tests/test_frames.py
Update couple of packages that were causing problems for Python 3.10 and start supporting it. Bump version to 0.2.6.
=> chore(packages): update packages

README.md, owid/catalog/utils.py, tests/test_utils.py
The original approach with `t.columns = ...` dropped metadata of colliding columns. Using `.rename(columns=` fixes that.
=> fix(underscore): keep metadata when resolving collisions

owid/catalog/catalogs.py, owid/catalog/meta.py, tests/test_catalogs.py
Reindexing of an entire catalog is slow (~10s) which is fine for bulk updates, but slow for fast-track. Add `include` argument to only reindex datasets matching given pattern and reuse all the other datasets from existing catalog.
=> feature(reindex): add `include` arg

owid/catalog/meta.py, tests/test_meta.py
dataclass_json is passing an extra `encode_json` argument that is breaking `to_json`
=> fix(meta): fix to_json for dataclasses

owid/catalog/catalogs.py
Remove mention of deprecated `explorer` channel in catalog.
Is there any other change to be made with this regard?
=> refactor(explorers): remove mention of deprecated explorer channel

owid/catalog/catalogs.py
Fixes https://github.com/owid/etl/issues/337
We now have multiple versions of some datasets, meaning that allowing users to filter to specific versions is more important than before.
This change adds filtering on this field to all find methods.
=> enhance: add version filtering to catalog find() method

owid/catalog/datasets.py, owid/catalog/tables.py, tests/test_datasets.py
Parquet is an efficient columnar format like Feather. We want to support both and render to both since some downstream consumers only support one of these formats, and Parquet is better supported than Feather generally.
Parquet supports a schema with additional metadata; we take advantage of that and serialise our table metadata into the schema on save, restoring it on write.
By default, we also change Dataset so that when you add a table, it serialises the table to all available formats including CSV unless specifically restricted.
=> feature: add parquet support and render to multiple files

owid/catalog/catalogs.py
Generate each channel index in parquet as well as feather, in order to support parquet-only clients.
=> Reindex to parquet as well as feather

owid/catalog/catalogs.py, owid/catalog/datasets.py, owid/catalog/tables.py, tests/test_datasets.py, tests/test_tables.py
Fixes #57
- Increase test coverage over parquet
- Fix edge case where parquet could not deserialise a table with no primary key
- Make use of generic `read_frame()` and `save_frame()` methods to avoid doing format detection everywhere
- Introduce a `PREFERRED_FORMAT` setting, which is currently `feather`
- Indicate in the static catalog all the formats that are supported for a table
- Clean up documentation across the board
=> fix: more throughly support parquet

owid/catalog/catalogs.py, owid/catalog/tables.py
Using `table.str.contains` lets us use regular expressions which are useful for tools like `compare` (we had two tables `faostat_ek` and `faostat_ek_flat` which can now be matched with `faostat_ek$`).
Needed by https://github.com/owid/etl/pull/452
=> enhance(catalog): improve error messaging and table matching

README.md, owid/catalog/catalogs.py, tests/test_catalogs.py
We typically use `find()` or `find_one()` for accessing into catalogs, even when we want something very specific.
There are two downsides to this:
1. These methods use substsring matching, so it can actually be impossible to uniquely specify a table this way
2. They have to load the entire catalog frame before giving you your data, even when the data itself is readily available
As an alternative, this change add path-based indexing into catalogs. For example, to get the `population` table:
```python
from owid import catalog
rc = catalog.RemoteCatalog()
pop = rc['garden/owid/latest/key_indicators/population']
```
=> feature: get a table with catalog[path] syntax

poetry.lock
Update package versions in lock file in order to fix a setuptools issue installing `ipdb` on Linux.
=> fix: setuptools issue installing ipdb on Linux

owid/catalog/tables.py, tests/test_tables.py
There was an error in ETL in case metadata of target table is incomplete. Fixed it and modified the test to catch this.
=> fix(tables): fix copy_from_metadata if target table has incomplete _fields

owid/catalog/catalogs.py
Small change: I think it's convenient if `find_latest` can ingest `version`. It finds the latest version of a dataset, given the specifications (if you specify the version, well, that's still the latest version). With this, we can basically replace `find_one` by `find_latest`, if we want to load either a specific version, or otherwise the latest.
=> feat(catalog): Let find_latest ingest version as an argument

owid/catalog/datasets.py, tests/test_datasets.py
`bool(dataset)` looks at its `__len__()` and if it is empty, it returns False. I think it should always return True so that we can safely do `if dataset` for optional arguments (this bit me a bit).
=> fix(dataset): bool(dataset) should be True even if it doesn't have any tables

README.md, owid/catalog/catalogs.py, owid/catalog/datasets.py, owid/catalog/meta.py, tests/test_datasets.py
I'd have found channel really useful when working on ETL tools. This PR adds `channel` to `DatasetMeta` and automatically fills it when saving the dataset.
This opens up a question - should we assume that all datasets will be saved with `[channel]/[namespace]/[version]/[short_name]` directory structure and implicitly set all these attributes? That would give us unique `uri` for every dataset. It's not very common, but I think there are some datasets with some of these attributes missing. It might also slightly simplify our code. I can't think of many uses cases for non-structured arbitrary paths besides somehow easier testing. To be fair, I don't think we gain much from this refactoring, perhaps it's better to keep status quo and keep this in the back of our heads.
=> enhance(datasetmeta): add channel to DatasetMeta

README.md, owid/catalog/tables.py, tests/test_datasets.py
Reading parquet format is [inefficient with lots of metadata](https://github.com/owid/etl/issues/783). Stop saving it to parquet and use JSON sidecar instead just like we do it for feather.
=> fix(tables): dont save metadata to parquet format

owid/catalog/datasets.py, owid/catalog/meta.py
Make things like `dataset: {}` in metadata unnecessary.
=> enhance(meta): optional metadata fields

owid/catalog/tables.py, owid/catalog/variables.py, tests/test_tables.py
`t["c"] = t["a"] + t["b"]` was previously erasing metadata of `t["a"]`. This happened when pandas tried to set `name` to `None`. We thought it was renaming and we renamed variable `a` to `None` in `_fields` dictionary. This PR don't modify `_fields` when we try to set None name.
=> fix(Tables): do not modify fields if name is None to fix pandas add operation

.vscode/settings.json, owid/catalog/tables.py, tests/test_tables.py
Fix for https://github.com/owid/owid-catalog-py/issues/81.
I'm not sure how well will this work in practice though. Pandas isn't keeping "metadata" by default when switching between index and column, so this is a bit of a hack.
=> :bug: keep metadata when calling set_index -> reset_index
